const API="http://localhost:5000/api";
async function adminFetch(path,options={}){const r=await fetch(API+path,{...options,headers:{...(options.headers||{}),Authorization:"Bearer "+(localStorage.getItem("dinehub_token")||"")}});const d=await r.json();if(!r.ok)throw Error(d.message||"Request failed");return d}
async function loadDashboard(){try{const d=await adminFetch("/admin/stats");document.getElementById("foodCount").textContent=d.foods;document.getElementById("orderCount").textContent=d.orders;document.getElementById("userCount").textContent=d.users}catch(e){["foodCount","orderCount","userCount"].forEach(x=>{const el=document.getElementById(x);if(el)el.textContent="—"})}}
async function loadFoods(){const box=document.getElementById("adminFoods");if(!box)return;try{const foods=await adminFetch("/foods");box.innerHTML=foods.map(f=>`<article class="food-card"><div class="food-image">${f.emoji||"🍽️"}</div><h3>${f.name}</h3><p>${f.category}</p><div class="food-bottom"><b>₹${f.price}</b><button class="small-btn" onclick="deleteFood('${f._id}')">Delete</button></div></article>`).join("")}catch(e){box.innerHTML='<div class="empty">Start backend and login as admin.</div>'}}
async function deleteFood(id){if(!confirm("Delete this food?"))return;try{await adminFetch("/foods/"+id,{method:"DELETE"});loadFoods()}catch(e){alert(e.message)}}
document.getElementById("foodForm")?.addEventListener("submit",async e=>{e.preventDefault();try{await adminFetch("/foods",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:foodName.value,price:Number(foodPrice.value),category:foodCategory.value,emoji:foodEmoji.value})});e.target.reset();loadFoods()}catch(x){alert(x.message)}})
async function loadAdminOrders(){const box=document.getElementById("adminOrders");if(!box)return;try{const data=await adminFetch("/admin/orders");box.innerHTML=data.map(o=>`<article class="order-card"><h3>#${o._id.slice(-6)}</h3><p>User: ${o.user?.email||"Unknown"}</p><p>Total: ₹${o.total}</p><p>Status: <span class="status">${o.status}</span></p></article>`).join("")}catch(e){box.innerHTML='<div class="empty">Start backend and login as admin.</div>'}}
async function loadUsers(){const box=document.getElementById("adminUsers");if(!box)return;try{const data=await adminFetch("/admin/users");box.innerHTML=data.map(u=>`<article class="order-card"><h3>${u.name}</h3><p>${u.email}</p><p>Role: ${u.role}</p></article>`).join("")}catch(e){box.innerHTML='<div class="empty">Start backend and login as admin.</div>'}}
loadDashboard();loadFoods();loadAdminOrders();loadUsers();
